Task20.1
psadovski/kodilla-course-task-app pull request #20
Opened 2018-10-01 12:13 UTC by psadovski

2018-10-01 12:14 UTC, psadovski commented
Zadanie 21.1

2018-10-01 18:11 UTC, mps4dev requested changes
w wielu miejscach te same uwagi.

2018-10-01 18:11 UTC, mps4dev commented on src/test/java/com/crud/tasks/mapper/TaskMapperTestSuite.java
> +        assertEquals((Long)1L, task.getId());
po co tu to rzutowanie?

2018-10-01 18:11 UTC, mps4dev commented on src/test/java/com/crud/tasks/mapper/TaskMapperTestSuite.java
> +    public void testMapToTask() {
nazwij lepiej metode: testTaskDtoToTask

2018-10-01 18:11 UTC, mps4dev commented on src/test/java/com/crud/tasks/mapper/TaskMapperTestSuite.java
> +    public void testMapToTaskWhenTaskDtoIsNull() {
podobnie z nazwa

2018-10-01 18:11 UTC, mps4dev commented on src/test/java/com/crud/tasks/mapper/TaskMapperTestSuite.java
> +    public void testMapToTaskDto() {
rowniez

2018-10-01 18:11 UTC, mps4dev commented on src/test/java/com/crud/tasks/mapper/TaskMapperTestSuite.java
> +        assertEquals((Long)1L, taskDto.getId());
po co rzutowanie?

2018-10-02 07:10 UTC, mps4dev requested changes
:-1:

2018-10-02 07:10 UTC, mps4dev commented on src/test/java/com/crud/tasks/mapper/TaskMapperTestSuite.java
> +        assertThat(taskDtoList.get(0).getId()).isEqualTo(1L);
a może spróbuj uzyć: `assertThat(taskDtoList.equals(Arrays.asList(new TaskDto(1L, "Title 1", "Content 1")))).isTrue();`

2018-10-02 08:33 UTC, mps4dev approved these changes
:+1:

2018-10-02 09:22 UTC, merged